### ISSUE TITLE
Doesn't work in Firefox currently

### ISSUE THREAD

**Issue by expenses** [wngr/wasm-futures-executor#4]
In Firefox I get this error:
```
Error message: SyntaxError: export declarations may only appear at top level of a module
URL: https://expenses.github.io/mateversum-web/pkg/snippets/wasm-futures-executor-7283b277ab0e797e/worker.js
Line Number: 5
```
~~Presumably this is caused by the fact that there's a comment here: https://github.com/wngr/wasm-futures-executor/blob/bafa85a68be4cf08017234bee70ce317d247be8c/worker.js#L1-L5~~

~~I'll test this when I have some time. If this is really the problem then that's mega-dumb.~~

**Comment by expenses** [comment]
Actually it's caused by exporting a function instead of a set.. or something. This gets past that error:

```javascript
function startWorker(module, memory, state, opts, helper) {
    const worker = new Worker(new URL('./worker.js',
        import.meta.url), opts);
    worker.postMessage([module, memory, state, helper.mainJS()]);

    return new Promise((res, rej) => {
      worker.onmessage = ev => {
        if (ev.data === 'started') res();
      };
      worker.onerror = rej;
    });
}

export { startWorker };
```
But then you get `SyntaxError: import.meta may only appear in a module` and I don't know enough about the funky way this file works to get past that.

**Comment by expenses** [comment]
Closing because I didn't read https://github.com/wngr/wasm-futures-executor#browser-support 😉

**Comment by mb720** [comment]
To fix the error
>SyntaxError: export declarations may only appear at top level of a module

when trying to use web worker with WASM, see also this very helpful repository: https://github.com/sgasse/wasm_worker_interaction
